# Generated by Django 2.2.8 on 2019-12-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191213_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Q', 'QUEUED'), ('C', 'COMPLETE'), ('P', 'PROCESSING'), ('F', 'FAILED')], max_length=1),
        ),
    ]
